#include "gpio_defs.h"




const gpio_def GpioDefsTab[MAX_GPIO] = 
{
	/* PORT A */
	ADD_GPIO_TO_TAB(A, 0),
	ADD_GPIO_TO_TAB(A, 1),
	ADD_GPIO_TO_TAB(A, 2),
	ADD_GPIO_TO_TAB(A, 3),
	ADD_GPIO_TO_TAB(A, 4),
	ADD_GPIO_TO_TAB(A, 5),
	ADD_GPIO_TO_TAB(A, 6),
	ADD_GPIO_TO_TAB(A, 7),
	ADD_GPIO_TO_TAB(A, 8),
	ADD_GPIO_TO_TAB(A, 9),
	ADD_GPIO_TO_TAB(A, 10),
	ADD_GPIO_TO_TAB(A, 11),
	ADD_GPIO_TO_TAB(A, 12),
	ADD_GPIO_TO_TAB(A, 13),
	ADD_GPIO_TO_TAB(A, 14),
	ADD_GPIO_TO_TAB(A, 15),
	
	/* PORT B */
	ADD_GPIO_TO_TAB(B, 0),
	ADD_GPIO_TO_TAB(B, 1),
	ADD_GPIO_TO_TAB(B, 2),
	ADD_GPIO_TO_TAB(B, 3),
	ADD_GPIO_TO_TAB(B, 4),
	ADD_GPIO_TO_TAB(B, 5),
	ADD_GPIO_TO_TAB(B, 6),
	ADD_GPIO_TO_TAB(B, 7),
	ADD_GPIO_TO_TAB(B, 8),
	ADD_GPIO_TO_TAB(B, 9),
	ADD_GPIO_TO_TAB(B, 10),
	ADD_GPIO_TO_TAB(B, 11),
	ADD_GPIO_TO_TAB(B, 12),
	ADD_GPIO_TO_TAB(B, 13),
	ADD_GPIO_TO_TAB(B, 14),
	ADD_GPIO_TO_TAB(B, 15),

	/* PORT C */
	ADD_GPIO_TO_TAB(C, 0),
	ADD_GPIO_TO_TAB(C, 1),
	ADD_GPIO_TO_TAB(C, 2),
	ADD_GPIO_TO_TAB(C, 3),
	ADD_GPIO_TO_TAB(C, 4),
	ADD_GPIO_TO_TAB(C, 5),
	ADD_GPIO_TO_TAB(C, 6),
	ADD_GPIO_TO_TAB(C, 7),
	ADD_GPIO_TO_TAB(C, 8),
	ADD_GPIO_TO_TAB(C, 9),
	ADD_GPIO_TO_TAB(C, 10),
	ADD_GPIO_TO_TAB(C, 11),
	ADD_GPIO_TO_TAB(C, 12),
	ADD_GPIO_TO_TAB(C, 13),
	ADD_GPIO_TO_TAB(C, 14),
	ADD_GPIO_TO_TAB(C, 15),

	/* PORT D */
	ADD_GPIO_TO_TAB(D, 0),
	ADD_GPIO_TO_TAB(D, 1),
	ADD_GPIO_TO_TAB(D, 2),
	ADD_GPIO_TO_TAB(D, 3),
	ADD_GPIO_TO_TAB(D, 4),
	ADD_GPIO_TO_TAB(D, 5),
	ADD_GPIO_TO_TAB(D, 6),
	ADD_GPIO_TO_TAB(D, 7),
	ADD_GPIO_TO_TAB(D, 8),
	ADD_GPIO_TO_TAB(D, 9),
	ADD_GPIO_TO_TAB(D, 10),
	ADD_GPIO_TO_TAB(D, 11),
	ADD_GPIO_TO_TAB(D, 12),
	ADD_GPIO_TO_TAB(D, 13),
	ADD_GPIO_TO_TAB(D, 14),
	ADD_GPIO_TO_TAB(D, 15),

	/* PORT E */

	ADD_GPIO_TO_TAB(E, 0),
	ADD_GPIO_TO_TAB(E, 1),
	ADD_GPIO_TO_TAB(E, 2),
	ADD_GPIO_TO_TAB(E, 3),
	ADD_GPIO_TO_TAB(E, 4),
	ADD_GPIO_TO_TAB(E, 5),
	ADD_GPIO_TO_TAB(E, 6),
	ADD_GPIO_TO_TAB(E, 7),
	ADD_GPIO_TO_TAB(E, 8),
	ADD_GPIO_TO_TAB(E, 9),
	ADD_GPIO_TO_TAB(E, 10),
	ADD_GPIO_TO_TAB(E, 11),
	ADD_GPIO_TO_TAB(E, 12),
	ADD_GPIO_TO_TAB(E, 13),
	ADD_GPIO_TO_TAB(E, 14),
	ADD_GPIO_TO_TAB(E, 15),


#ifdef GPIOF
	/* PORT F */

	ADD_GPIO_TO_TAB(F, 0),
	ADD_GPIO_TO_TAB(F, 1),
	ADD_GPIO_TO_TAB(F, 2),
	ADD_GPIO_TO_TAB(F, 3),
	ADD_GPIO_TO_TAB(F, 4),
	ADD_GPIO_TO_TAB(F, 5),
	ADD_GPIO_TO_TAB(F, 6),
	ADD_GPIO_TO_TAB(F, 7),
	ADD_GPIO_TO_TAB(F, 8),
	ADD_GPIO_TO_TAB(F, 9),
	ADD_GPIO_TO_TAB(F, 10),
	ADD_GPIO_TO_TAB(F, 11),
	ADD_GPIO_TO_TAB(F, 12),
	ADD_GPIO_TO_TAB(F, 13),
	ADD_GPIO_TO_TAB(F, 14),
	ADD_GPIO_TO_TAB(F, 15),

#endif

#ifdef GPIOG
	/* PORT G */

	ADD_GPIO_TO_TAB(G, 0),
	ADD_GPIO_TO_TAB(G, 1),
	ADD_GPIO_TO_TAB(G, 2),
	ADD_GPIO_TO_TAB(G, 3),
	ADD_GPIO_TO_TAB(G, 4),
	ADD_GPIO_TO_TAB(G, 5),
	ADD_GPIO_TO_TAB(G, 6),
	ADD_GPIO_TO_TAB(G, 7),
	ADD_GPIO_TO_TAB(G, 8),
	ADD_GPIO_TO_TAB(G, 9),
	ADD_GPIO_TO_TAB(G, 10),
	ADD_GPIO_TO_TAB(G, 11),
	ADD_GPIO_TO_TAB(G, 12),
	ADD_GPIO_TO_TAB(G, 13),
	ADD_GPIO_TO_TAB(G, 14),
	ADD_GPIO_TO_TAB(G, 15),

#endif

#ifdef GPIOH
	/* PORT H */

	ADD_GPIO_TO_TAB(H, 0),
	ADD_GPIO_TO_TAB(H, 1),
	ADD_GPIO_TO_TAB(H, 2),
	ADD_GPIO_TO_TAB(H, 3),
	ADD_GPIO_TO_TAB(H, 4),
	ADD_GPIO_TO_TAB(H, 5),
	ADD_GPIO_TO_TAB(H, 6),
	ADD_GPIO_TO_TAB(H, 7),
	ADD_GPIO_TO_TAB(H, 8),
	ADD_GPIO_TO_TAB(H, 9),
	ADD_GPIO_TO_TAB(H, 10),
	ADD_GPIO_TO_TAB(H, 11),
	ADD_GPIO_TO_TAB(H, 12),
	ADD_GPIO_TO_TAB(H, 13),
	ADD_GPIO_TO_TAB(H, 14),
	ADD_GPIO_TO_TAB(H, 15),

#endif

};


gpio_val_s GpioValTab[MAX_GPIO];